'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NHIS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property account_box_100dp_0000F5_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account_box_100dp_0000F5_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property account_box_100dp_E3E3E3_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account_box_100dp_E3E3E3_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property account_circle_16dp_E3E3E3_FILL0_wght400_GRAD0_opsz20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account_circle_16dp_E3E3E3_FILL0_wght400_GRAD0_opsz20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property account_circle_25dp_9AB17A_FILL0_wght400_GRAD0_opsz24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account_circle_25dp_9AB17A_FILL0_wght400_GRAD0_opsz24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property account_circle_25dp_E3E3E3_FILL0_wght400_GRAD0_opsz24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account_circle_25dp_E3E3E3_FILL0_wght400_GRAD0_opsz24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Component_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Component 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Health() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Health", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Splashscreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splashscreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property total_shape_yn8KzjHGtak_unsplash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("total-shape-yn8KzjHGtak-unsplash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vecteezy_assorted_colorful_pharmaceutical_capsules_and_dietary_81288216() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vecteezy_assorted-colorful-pharmaceutical-capsules-and-dietary_81288216", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
